baseURL = 'http://sloughter.dev/'
languageCode = 'en-us'
title = 'sloughter.dev'
enableInlineShortcodes = true

[params]
  # color style
  color = 'linen'

  disableThemeToggle = true

  twitter = 't_sloughter'
  github = 'tsloughter'
  linkedin = 'tristan-sloughter-4368b513'

  avatar = 'tristan@sloughter.dev'
  name = 'Tristan Sloughter'
  bio = 'Erlang and OpenTelemetry Accessories'

  [params.profileMode]
    enabled = true
    title = "Tristan Sloughter"
    subtitle = "Erlang and OpenTelemetry Accessories"
    imageUrl = "https://en.gravatar.com/userimage/143547863/c184a87cce81f183b54b5c1e1a8e5f37.jpg?size=500"
    imageWidth = 220
    imageHeight = 220
    imageTitle = "Winnie"

  [[params.profileMode.buttons]]
    name = "Adopting Erlang"
    url = "https://adoptingerlang.org/"

  [[params.profileMode.buttons]]
    name = "How I Start"
    url = "https://howistart.org/"

  [[params.profileMode.buttons]]
    name = "Rebar3"
    url = "https://rebar3.org/"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/tsloughter"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/tristan-sloughter-4368b513/"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/t_sloughter"


[menu]

  [[menu.main]]
    identifier = "uses"
    name = "uses"
    url = "/uses/"
    weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.imports]]
    # path = "github.com/nanxiaobei/hugo-paper"
    path = "github.com/adityatelange/hugo-PaperMod"